browser=chrome
baseUrl=http://localhost:5173/
explicitWait=10
screenshotsPath=reports/screenshots/
reportsPath=reports/extent/
dataPath=src/test/resources/data.xlsx
default.email=ayoubamzil@gmail.com
default.password=ayoub123_